#!/usr/bin/sh

DIST_DIR=dist/
HASHMAP_DIR=$DIST_DIR/hashmap/

# Clean existing dist
rm -rf $DIST_DIR

# Create the dir
mkdir -p $HASHMAP_DIR

# Copy the files
cp -r ./include     $HASHMAP_DIR/include
cp -r ./src         $HASHMAP_DIR/src
cp -r example/      $HASHMAP_DIR/example
cp -r test/         $HASHMAP_DIR/test
cp CMakeLists.txt   $HASHMAP_DIR/CMakeLists.txt
cp LICENSE          $HASHMAP_DIR/LICENSE
cp README.md        $HASHMAP_DIR/README.md

# Move into dist/ dir
cd $DIST_DIR

# Compress with tar + gzip
tar -cvf hashmap-1.0.tar.gz hashmap

# Compress with zip
zip -r hashmap-1.0.zip hashmap
